name: 构建 Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: 构建 APK
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: 赋予 Gradle 执行权限
        run: chmod +x gradlew

      - name: 构建 Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: 构建 Release APK
        run: ./gradlew assembleRelease --stacktrace

      - name: 上传 Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: 上传 Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release-unsigned.apk

      - name: 获取提交信息
        id: commit
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "commit_msg=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
          echo "commit_date=$(git log -1 --format=%cd --date=format:'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: 创建 Release（仅 main 分支）
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ steps.commit.outputs.commit_date }}-${{ steps.commit.outputs.sha_short }}
          name: 自动构建 ${{ steps.commit.outputs.commit_date }}
          body: |
            **提交信息**: ${{ steps.commit.outputs.commit_msg }}
            **提交SHA**: ${{ github.sha }}
            **构建时间**: ${{ steps.commit.outputs.commit_date }}
            
            ### 下载说明
            - `app-debug.apk` - Debug版本，适合开发测试
            - `app-release-unsigned.apk` - Release版本（未签名）
            
            ### 安装方法
            ```bash
            adb install app-debug.apk
            ```
          files: |
            app/build/outputs/apk/debug/app-debug.apk
            app/build/outputs/apk/release/app-release-unsigned.apk
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

